routes/web.php
<?php

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

//what
Route::resource('/auth', 'UserController');

Route::get('/auth/{auth}/chenagepassword', 'UserController@changepassword')->name('changepassword');
Route::put('/auth/{auth}/updatepassword', 'UserController@updatepassword')->name('updatepassword');

Route::put('/auth/{auth}/photoupdate', 'UserController@photoupdate')->name('photoupdate');


Route::get('/errors', 'HomeController@error403')->name('errors.403');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/welcome', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('search', 'OwnerController@search')->name('search');


Route::get('/log', 'ActivitylogController@index')->name('activitylog');

Route::get('/lands/createland', 'LandController@createland')->name('lands.createland');
Route::get('/lands/transfer', 'LandController@transfer')->name('lands.transfer');

Route::get('/lands/payment', 'LandController@payment')->name('lands.payment');


Route::resource('owners', 'OwnerController');
Route::resource('lands', 'LandController');


Route::get('/lands.maps', 'LandController@maps')->name('lands.maps');
Route::get('/lands.addmaps', 'LandController@addmaps')->name('lands.addmaps');

app/owner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class owner extends Model
{


  use LogsActivity;

  protected $fillable = [
    'fname','sname','tname','address','photo','gender','phone','pid', 'email', 'dob','user_id',
                        ];

  protected static $logFillable = true;

  public function getLogNameToUse(string $eventName = ''): string
      {
         return 'Owner';
      }

      public function getDescriptionForEvent(string $eventName): string
    {

      $model ='owner Management';

      return "The $model model has been {$eventName}";

    }

          public function user()
           {
               return $this->belongsTo(user::class);
           }


           public function lands()
            {
             return $this->hasMany(land::class);
            }



}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Crypt;
use App\Http\Controllers\Controller;
use App\owner;
use App\User;
use App\land;
use Auth;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;
use DB;
use Illuminate\Http\Request;

class OwnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


     public function __construct()
     {
       $this->middleware('role:superadministrator|admin|owners');
     }


    public function index()
    {
        $owners =owner::latest()->get();;
        return view('owners.index', compact('owners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

      return view('owners.create');

    }
    public function search(Request $request)
    {

        $term = $request->term;

        $owners = owner::where('fname','LIKE', '%'.$term.'%')
                        ->orwhere('sname', 'LIKE', '%'.$term.'%')
                        ->orwhere('pid', 'LIKE', '%'.$term.'%')
                        ->select(DB::raw(
                          'pid, fname,
                           sname'

                        ))->get();


        // $owners1 = owner::where('fname', 'LIKE', '%'.$term.'%')->get();

        if(count($owners) == 0){
        $search[] = 'No owner found !';
        }else {
          foreach($owners as $owner){
            $pid= $owner->pid;
            $fname= $owner->fname;
            $sname= $owner->sname;
            $owner= $pid.": ".$fname." ".$sname; 
            $search[] = $owner;

          }

          }

          return $search;


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */


    public function store(request $request)
    {
          $validatedData = $request->validate([
           'photo' => 'required|image',
           'fname' => 'required|string|max:25',
           'sname' => 'required|string|max:25',
           'tname' => 'required|string|max:25',
           'fthname' => 'required|string|max:25',
           'tname' => 'required|string|max:25',
           'pid' => 'required|string|max:15|unique:owners',
           'type' => 'required|string|max:15|',
           'town' => 'required|string|max:50',
           'line' => 'required|string|max:50',
           'zone' => 'required|string|max:50',
           'dob' => 'required|date|after:01.01.1915|before:today',
           'gender' => 'required|string|max:8',
           'phone' => 'required|string|max:12',
           'email' => 'nullable|email|max:255|unique:owners',
        ]);
          //dd(Request()->all());
          $owner = new owner;
          $owner->fname = request('fname');
          $owner->sname = request('sname');
          //$owner->sname = encrypt(request('sname'));
          $owner->tname = request('tname');
          $owner->fthname = request('fthname');
          $owner->mother = request('mother');
          $owner->pid = request('pid');
          $owner->type = request('type');
          $owner->dob = request('dob');
          $owner->town = request('town');
          $owner->line = request('line');
          $owner->zone = request('zone');
          $owner->email = request('email');
          $owner->phone = request('phone');
          $owner->gender = request('gender');


              $path = $request->photo->store('photos');
              $store = $request->photo->store('public/photos');
              $owner->photo = $path;


          $owner->user_id =Auth::id();
          $owner->save();
          //return redirect('/owners');
          return redirect()->route('owners.index')->with('success','owner Created');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\owner  $owner
     * @return \Illuminate\Http\Response
     */
    public function show(owner $owner)
    {
      //$lands =land::with('owner')->get();
      $owners = owner::with('lands')->get();
      return view('owners.show', compact('owner', 'land'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\owner  $owner
     * @return \Illuminate\Http\Response
     */
    public function edit(owner $owner)
    {
      return view('owners.edit', compact('owner'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\owner  $owner
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

      //dd(Request()->all());
      //$id= request('id');
      $owner =owner::findOrFail($id);
      $owner->fname = request('fname');
      $owner->sname = request('sname');
      $owner->tname = request('tname');
      $owner->pid = request('pid');
      $owner->dob = request('dob');
      $owner->address = request('address');
      $owner->email = request('email');
      $owner->phone = request('phone');
      $owner->gender = request('gender');
      $owner->photo = request('photo');
      $owner->user_id =Auth::id();
      $owner->save();
      return redirect('/owners');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\owner  $owner
     * @return \Illuminate\Http\Response
     */
    public function destroy(owner $owner)
    {
        //
    }
}

resources/views/owners/create.blade.php
@extends('layouts/default')

{{-- Page title --}}
@section('title')
    Dashboard
    @parent
@stop
{{-- page level styles --}}
@section('header_styles')
    <!--Plugin styles-->
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/select2/css/select2.min.css')}}" />
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css')}}"/>
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/bootstrapvalidator/css/bootstrapValidator.min.css')}}"/>
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/c3/css/c3.min.css')}}"/>
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/switchery/css/switchery.min.css')}}" />

@stop


{{-- Page content --}}
@section('content')
    <header class="head">
        <div class="main-bar">
            <div class="row">
                <div class="col-6">
                    <h4 class="m-t-5">
                        <i class="fa fa-home"></i>
                        Dashboard
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="outer">
        <div class="inner bg-container">
          <div class="row">
                                  <div class="col-lg-12">
                                      <div class="card">
                                        @if ($errors->any())
                                          <div class="alert alert-danger">
                                            <ul>
                                              @foreach ($errors->all() as $error)
                                              <h4><li>{{ $error }}</li></h4>
                                              @endforeach
                                              </ul>
                                            </div>
                                            @endif
                                          <div class="card-header bg-warning">
                                              Register New Land Owner
                                          </div>
                                          <div class="card-block">
                                            <div class="row">
                                              <form method="POST" action="{{ route('owners.store') }}" enctype="multipart/form-data">
                                                {{ csrf_field() }}
                                              <div class="form-group row m-t-25">
                                   <div class="col-lg-3 text-center text-lg-right">
                                       <label class="col-form-label">Owner Pic</label>
                                   </div>
                                   <div class="col-lg-6 text-center text-lg-left">
                                       <div class="fileinput fileinput-new" data-provides="fileinput">
                                           <div class="fileinput-new img-thumbnail text-center">
                                               <img src="#" data-src="holder.js/100%x100%"  alt="not found"></div>
                                           <div class="fileinput-preview fileinput-exists img-thumbnail"></div>
                                           <div class="m-t-20 text-center">
                                             <span class="btn btn-primary btn-file">
                                                  <span class="fileinput-new">Select image</span>
                                                  <span class="fileinput-exists">Change</span>
                                                  <input type="file" value="{{ old('photo') }}"  required name="photo"></span>
                                               <a href="#" class="btn btn-warning fileinput-exists"
                                                  data-dismiss="fileinput">Remove</a>
                                           </div>
                                       </div>
                                   </div>
                               </div>
                                            </div>

                                <div class="row">

                                                  <div class="col-lg-6 input_field_sections">

                                                      <h5>First</h5>
                                                        <input class="form-control" value="{{ old('fname') }}" placeholder="First Name" name="fname" type="text" id="fname">

                                                  </div>

                                                  <div class="col-lg-6 input_field_sections">
                                                      <h5>Second Name</h5>
                                                        <input class="form-control" value="{{ old('sname') }}"  placeholder="Second Name" required="" name="sname" type="text" id="fname">

                                                  </div>
                                    </div>
                                    <div class="row">

                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Third Name</h5>
                                            <input class="form-control" value="{{ old('tname') }}"  placeholder="Third Name" required="" name="tname" type="text" id="tname">
                                      </div>
                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Fourth Name</h5>
                                            <input class="form-control" value="{{ old('fthname') }}"  placeholder="Fourth  Name" required="" name="fthname" type="text" id="fthname">
                                      </div>

                                    </div>
                                    <div class="row">
                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Gender</h5>
                                          <label class="btn btn-primary">
                                          <input  type="radio" name="gender" value="male" checked> Male </label>
                                          <label class="btn btn-primary">

                                          <input type="radio" name="gender" value="female"> Female<br></label>
                                        </div>
                                        <div class="col-lg-6 input_field_sections">
                                            <h5>Date of Birth</h5>
                                              <input class="form-control" value="{{ old('dob') }}"  placeholder="11/11/1111" required="" name="dob" type="date" id="dob">
                                        </div>


                                    </div>

                                    <div class="row">
                                      <div class="col-lg-2 input_field_sections">
                                          <h5>Type</h5>
                                          <!-- <label for="exampleFormControlSelect1">Example select</label> -->
                                           <select name="type" class="form-control" id="exampleFormControlSelect1">
                                             <option value="Puntland">Puntland ID</option>
                                             <option value="Passport">Passport ID</option>
                                             <option value="Rufugee">Rufugee ID</option>
                                           </select>
                                      </div>
                                      <div class="col-lg-4 input_field_sections">
                                          <h5>ID</h5>
                                            <input class="form-control" value="{{ old('pid') }}"  placeholder="989876" required="" name="pid" type="number" id="pid">
                                      </div>

                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Mother's Full Name</h5>
                                            <input class="form-control" value="{{ old('mother') }}"  placeholder="Hooyada Magaceed" required="" name="mother" type="text" id="mother">
                                      </div>
                                        </div>

                                    <div class="row">
                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Town</h5>
                                            <input class="form-control" value="{{ old('town') }}"  placeholder="Tuulada" required="" name="town" type="text" id="town">
                                      </div>
                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Line</h5>
                                            <input class="form-control" value="{{ old('line') }}"  placeholder="Laanta" required="" name="line" type="text" id="line">
                                      </div>

                                      <div class="col-lg-6 input_field_sections">
                                          <h5>Zone</h5>
                                            <input class="form-control" value="{{ old('zone') }}"  placeholder="zone" required="" name="zone" type="text" id="zone">
                                      </div>
                                    </div>


                                        <div class="row">
                                          <div class="col-lg-6 input_field_sections">
                                                    <h5>Phone Number</h5>
                                                    <input class="form-control" value="{{ old('phone') }}"  placeholder="090-6666666" required="" name="phone" type="number" id="phone">
                                                </div>
                                                <div class="col-lg-6 input_field_sections">
                                                    <h5>Email</h5>
                                                    <input class="form-control" value="{{ old('email') }}"  placeholder="abc@abc.com"  name="email" type="email" id="email">
                                                </div>
                                          </div>
                                          <div class="row">
                                            <div class="col-lg-9 push-lg-3">
                                              <input class="btn btn-primary offset-10" type="submit" value="Create">
                                              </form>

                                            </div>


                                          </div>

                                          </div>
                                      </div>
                                  </div>
                              </div>

            <!-- /.inner -->
        </div>
        <!-- /.outer -->
    </div>
    <!-- /.outer -->
@stop
{{-- page level scripts --}}
@section('footer_scripts')
    <!--  plugin scripts -->
    <script type="text/javascript" src="{{asset('assets/js/pluginjs/jasny-bootstrap.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/holderjs/js/holder.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/bootstrapvalidator/js/bootstrapValidator.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/js/pages/validation.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/raphael/js/raphael-min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/d3/js/d3.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/c3/js/c3.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/toastr/js/toastr.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/switchery/js/switchery.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.js')}}" ></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.resize.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.stack.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.time.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotspline/js/jquery.flot.spline.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.categories.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.pie.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/jquery_newsTicker/js/newsTicker.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/countUp.js/js/countUp.min.js')}}"></script>
    <!--end of plugin scripts-->
    <script type="text/javascript" src="{{asset('assets/js/pages/new_dashboard.js')}}"></script>
    <!-- end page level scripts -->
@stop

resources/views/owners/show.blade.php
@extends('layouts/default')

{{-- Page title --}}
@section('title')
    Owner Info
    @parent
@stop
{{-- page level styles --}}
@section('header_styles')
<!--plugin styles-->
<link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/select2/css/select2.min.css')}}" />
<link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/datatables/css/scroller.bootstrap.min.css')}}" />
<link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/datatables/css/colReorder.bootstrap.min.css')}}" />
<link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/datatables/css/dataTables.bootstrap.min.css')}}" />
<link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/dataTables.bootstrap.css')}}" />
<link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/invoice.css')}}">

<!-- end of plugin styles -->
<!--Page level styles-->
<!--End of page level styles-->
<style media="screen">
  #pic{
    height:200px;
    width:300px;
  }
</style>
@stop


{{-- Page content --}}
@section('content')
    <header class="head">
        <div class="main-bar">
            <div class="row">
                <div class="col-6">
                    <h4 class="m-t-5">
                        <i class="fa fa-home"></i>
                        Dashboard
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="outer">
      <div class="inner bg-light lter bg-container">
        <div class="row">

        <div class="col-12">
          @role('superadministrator|admin')
          <div class="btn-group">
          <a href="{{url('lands/create')}}?id={{$owner->id}}" class="btn btn-primary">
          Register New Land
          <i class="fa fa-plus"></i>
          </a>
          </div>
          @endrole
          <div class=" invoice_print float-right" >
                    <span class="pull-sm-right">
                        <a style="color:#fff;" class="btn button-alignment btn-info m-t-15" data-toggle="button" onclick="javascript:window.print();">
                            Print
                        </a>
                    </span>
          </div>
          <div class="btn-group float-right">
          </div>
        </div>
      </div>


<br>
      <div class="card">

        <h4 class="card-title"></h4>
        <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <div class="card-header bg-info">
                <div>
                    <i class="fa fa-user"></i>
                    Owner Picture
                </div>
            </div>
            <div class="card-body">
                        <div class="pic">
                          <img src="/storage/{{$owner->photo}}" alt="" width="200" height="200">
                        </div>

            </div>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="card ">

            <div class="card-header bg-info">
                <div>
                    <i class="fa fa-user"></i>
                    Owner Info (Registraton ID:{{ $owner->id }})
                </div>
            </div>

              <div class="bg-warning m-t-35 header_alignr">

              <h4 class="card-title">
                <table class="table"
                         id="editable_table" data-order='[[ 5, "dec" ]]' role="grid">                <tr>

                           <tr>
                             <th>ID:</th>
                             <td>{{ $owner->type }}: {{ $owner->pid }}</td>
                           </tr>
              <tr>
                  <th>Full name: </th>
                  <span>
                <td>{{ $owner->fname }}
                  {{ $owner->sname }}
                  {{ $owner->tname }}
                {{ $owner->fthname }}</td>
                  </tr></span>


              <tr>
                <th>Date of Birth:</th>
                <td>{{ $owner->dob }}</td>
            </tr>

            <tr>
              <th>Gender:</th>
              <td>{{ $owner->gender }}</td>
          </tr>
          <tr>
            <th>Mother's Name:</th>
            <td>{{ $owner->mother }}</td>
        </tr>

          <tr>
            <th>Town:</th>
            <td>{{ $owner->town }}</td>
        </tr>
        <tr>
          <th>Laanta:</th>
          <td>{{ $owner->line }}</td>
      </tr>
      <tr>
        <th>Zone:</th>
        <td>{{ $owner->zone }}</td>
    </tr>
    <tr>
      <th>Phone:</th>
      <td>{{ $owner->phone }}</td>
  </tr>
                <tr>
                  <th>Date Created: </th>
                  <td>{{ $owner->created_at->format('m/d/Y') }}</td>
              </tr>
              <tr>
                <th>Date Updated: </th>
                <td>{{ $owner->updated_at->format('m/d/Y') }}</td>
            </tr>

          </h4>
        </table>


            </div>

          </div>
          <br>
        </div>
      </div>
      </div>
    </div>
<!-- new div row 2-->


                        <!-- second column -->

                        <div class="row">

                        <div class="col-lg-12">
                            <div class="card m-t-35">
                                <div class="card-header bg-info">
                                    <div>
                                        <i class="fa fa-pencil"></i>
                                        Owner's Land
                                    </div>
                                </div>
                                <div class="card-block m-t-35 padding">
                                    <div class="feed">
                                      Number of Land(s)<span class="badge badge-pill badge-primary float-right">{{count($owner->lands)}}</span>

                                      <table class="table table-responsiv">
                                        <tr>
                                          <td>Town</td>
                                        <td>Latitude</td>
                                        <td>Longitude</td>
                                        <td>laanta</td>
                                        <td>Area of land</td>
                                        <td class="action">Action</td>
                                      </tr>

                                      @foreach($owner->lands as $land)
                                      <tr>

                                        <td>{{$land->town}}</td>
                                        <td>{{$land->latitude}}</td>
                                        <td>{{$land->longitude}}</td>
                                        <td>{{$land->laanta}}</td>
                                        <td>{{$land->areaofland}}</td>

                                        <td class="no-sort no-click" id="bread-actions">

                                          <a href="{{route('lands.show', [$land->id])}}" title="View" class="btn btn-sm btn-warning pull-right">
                                          <i class="fa fa-eye"></i> <span class="hidden-xs hidden-sm">View   </span>
                                          </a>
                                          <a href="{{route('lands.edit', [$land->id])}}" title="Edit" class="btn btn-sm btn-warning pull-right">
                                          <i class="fa fa-eye"></i> <span class="hidden-xs hidden-sm">Edit   </span>
                                          </a>


                                        </td>

                                      </tr>

                                      @endforeach
                                    </table>
                                    </div>
                                </div>
                            </div>
                        </div>

              </div>
          </div>
      </div>
        <!-- /.outer -->
    </div>
    <!-- /.outer -->
@stop
{{-- page level scripts --}}
@section('footer_scripts')
<!--plugin scripts-->
  <script type="text/javascript" src="{{asset('assets/vendors/select2/js/select2.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/js/pluginjs/dataTables.tableTools.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.colReorder.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.buttons.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.responsive.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.rowReorder.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.colVis.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.html5.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.bootstrap.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.print.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.scroller.min.js')}}"></script>
  <!-- end of plugin scripts -->
  <!--Page level scripts-->
  <script type="text/javascript" src="{{asset('assets/js/pages/datatable.js')}}"></script>
    <!-- end page level scripts -->
@stop