routes/web.php
<?php

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

//what
Route::resource('/auth', 'UserController');

Route::get('/auth/{auth}/chenagepassword', 'UserController@changepassword')->name('changepassword');
Route::put('/auth/{auth}/updatepassword', 'UserController@updatepassword')->name('updatepassword');

Route::put('/auth/{auth}/photoupdate', 'UserController@photoupdate')->name('photoupdate');


Route::get('/errors', 'HomeController@error403')->name('errors.403');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('/welcome', 'HomeController@welcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('search', 'OwnerController@search')->name('search');


Route::get('/log', 'ActivitylogController@index')->name('activitylog');

Route::get('/lands/createland', 'LandController@createland')->name('lands.createland');
Route::get('/lands/transfer', 'LandController@transfer')->name('lands.transfer');

Route::get('/lands/payment', 'LandController@payment')->name('lands.payment');


Route::resource('owners', 'OwnerController');
Route::resource('lands', 'LandController');


Route::get('/lands.maps', 'LandController@maps')->name('lands.maps');
Route::get('/lands.addmaps', 'LandController@addmaps')->name('lands.addmaps');

app/land.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class land extends Model
{


    use LogsActivity;

  protected $fillable = [
    'type', 'town', 'laanta', 'zone', 'width','length', 'areaofland', 'latitude', 'longitude', 'north', 'west',
'east', 'south', 'witness1', 'witness2', 'witness3', 'owner_id', 'user_id',
  ];

  protected static $logFillable = true;

  public function getLogNameToUse(string $eventName = ''): string
  {
     return 'Land';
  }
    public function getDescriptionForEvent(string $eventName): string
  {
        $model ='land Management';

          return "The $model model has been {$eventName}";
  }


        public function owner()
         {
             return $this->belongsTo(owner::class);
         }
         public function user()
                  {
                      return $this->belongsTo(user::class);
                  }
}

app/Http/Controllers/LandController.php
<?php

namespace App\Http\Controllers;

use App\land;
use App\owner;
use App\User;
use App\payment;
use Auth;

use Illuminate\Http\Request;

class LandController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
       $this->middleware('role:superadministrator|admin|lands');
     }
    public function index()
    {
        //dd(Request()->all());

        //$lands =land::all();
        $owners =owner::all();
        $lands =land::with('user', 'owner')->take(10)->latest()->get();
        return view('lands.index', compact('lands','owners'));
    }

    public function payment()
    {
      $lands =land::all();
      $owners =owner::all();
        return view('lands.payment', compact('lands', 'owners'));
    }

    public function search(Request $request)
        {

            $term = $request->term;
            $owners = owner::where('fname', 'LIKE', '%'.$term.'%')->get();
            //return $owner;
            if(count($owners) == 0){
                $searchResult[] = 'No owners found !';
            }else{
                foreach($owners as $owner){
                    $searchResult[] = $owner->searchItem;
                }
            }
            return $searchResult;
          }




    public function transfer()
    {

        $lands =land::with('user', 'owner')->take(10)->latest()->get();
        return view('lands.transfer', compact('lands'));
    }


    public function maps()
    {
      //dd(Request()->all());

        $lands =land::all();
        return view('lands.maps', compact('lands'));
    }
    public function addmaps()
    {
        $lands =land::all();
        return view('lands.addmaps', compact('lands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(request $request)
    {
      $id= request('id');
      $owner =owner::findOrFail($id);
      return view('lands.create', compact('owner'));

    }

    public function createland(request $request)
    {
      return view('lands.createland', compact('owner'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd(Request()->all());
        $land = new land;
        $land->type =  request('type');
        $land->town =  request('town');
        $land->laanta =  request('line');
        $land->zone =  request('zone');
        $land->length =  request('length');
        $land->width =  request('width');
        $land->areaofland =request('length')*request('width');
        $land->latitude =  request('latitude');
        $land->longitude =  request('longitude');
        $land->north = request('north');
        $land->west =  request('west');
        $land->east =  request('east');
        $land->south = request('south');
        $land->witness1 =request('witness1');
        $land->witness2 =request('witness2');
        $land->witness3 =request('witness3');
        //$land->owner_id =request('owner_id');
        $land->user_id =Auth::id();
        $land->save();
        return redirect('/lands');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\land  $land
     * @return \Illuminate\Http\Response
     */
    public function show(land $land)
    {

         $lands = land::all();
         return view('lands.show', compact('land', 'owner'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\land  $land
     * @return \Illuminate\Http\Response
     */
    public function edit(land $land)
    {
      $id= request('id');
      $owner =owner::find($id);
      $transfers =owner::all();
      return view('lands.edit', compact('land','owner','transfers'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\land  $land
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, land $land)
    {
          //dd(Request()->all());
          $id= request('id');
          $owner =owner::find($id);
          $land->type =  request('type');
          $land->town =  request('town');
          $land->laanta =  request('line');
          $land->zone =  request('zone');
          $land->length =  request('length');
          $land->width =  request('width');
          $land->areaofland =request('length')*request('width');
          $land->latitude =  request('latitude');
          $land->longitude =  request('longitude');
          $land->north = request('north');
          $land->west =  request('west');
          $land->east =  request('east');
          $land->south = request('south');
          $land->witness1 =request('witness1');
          $land->witness2 =request('witness2');
          $land->witness3 =request('witness3');
          $land->owner_id =request('owner_id');
          $land->user_id =Auth::id();
          $land->save();
          return redirect('/lands');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\land  $land
     * @return \Illuminate\Http\Response
     */
    public function destroy(land $land)
    {
        //
    }
}

resources/views/lands/addmaps.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>cool</title>
    <link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/maps.css')}}"/>

    <style media="screen">
    #map {
      /*height: 400px;
      width: 500px;*/
     }
    </style>
  </head>
  <body>


    <div class="row">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card m-t-35">
            <div class="card-header bg-warning">
                Galkacyo Map
            </div>
            <div class="card-block m-t-35">

                <br />
                <div id="map" class="gmap"></div>
            </div>
        </div>
    </div>

<script>

function initMap() {
var map = new google.maps.Map(document.getElementById('map'), {
  zoom: 13,
  center: {lat: 6.787436, lng: 47.441410},
  mapTypeId: 'satellite'
});

var marker = new google.maps.Marker({
    position: {
      lat: 6.791367,
      lng: 47.458487
    },
    map:map,
    draggable:true
  });
    google.maps.event.addListener(marker, 'dragend', function(){
      var lat =marker.getPosition().lat();
      var lng =marker.getPosition().lng();
      $('#lat').val(lat);
      $('#lng').val(lng);
  });
}
    </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDGt7x_fDW-0NNnuIw6TBGuPWFPTWdh0-I&callback=initMap">
    </script>
  </body>
</html>

resources/views/lands/create.blade.php
@extends('layouts/default')

{{-- Page title --}}
@section('title')
    Dashboard
    @parent
@stop
{{-- page level styles --}}
@section('header_styles')
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/chartist/css/chartist.min.css')}}" />
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/circliful/css/jquery.circliful.css')}}">
    <link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/index.css')}}">
@stop
@section('content')

    <header class="head">
        <div class="main-bar">
            <div class="row no-gutters">
                <div class="col-6">
                    <h4 class="m-t-5">
                        <i class="fa fa-home"></i>
                        Dashboard
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="outer">

  <div class="outer">
    <div class="row">
      <div class="col-12">
        @include('lands.addmaps')

      </div>

    </div>
      <div class="inner bg-container">
<br><br>
        <div class="container">
          <form method="POST" action="{{ route('lands.store') }}" accept-charset="UTF-8">
            {{ csrf_field() }}
            <input class="form-control" hidden="" type="number" name="owner_id" value="{{$owner->id}}">
          <div class="row">
            <div class="col-sm">
              <h5>Latitude</h5>
              <div class="form-group">
                <input class="form-control" type="text" required id="lat"  name="latitude" value="">
              </div>

            </div>
              <div class="col-sm">
              <h5>Longitude</h5>
              <div class="form-group">
                <input class="form-control" required type="text" id="lng"  name="longitude" value="">
              </div>
            </div>

          </div>
          <div class="row">
            <div class="col-sm">
              <h5>Land Type</h5>
              <div class="form-group">
                  <select required="" name="type" required class="form-control">
                    <option value="">Select Project Land Type</option>
                      <option value="Deegaan">Deegaan</option>
                      <option value="Ganacsi">Ganacsi</option>
                      <option value="Beerid">Beerid</option>
                    </select>
              </div>

            </div>
              <div class="col-sm">
                <h5>Town</h5>
                <div class="form-group">
                    <select required name="town" class="form-control">
                      <option value="">Select Town</option>
                        <option value="Israac">Israac</option>
                        <option value="Garsoor">Garsoor</option>
                        <option value="Barwaaqo">barwaaqo</option>
                      </select>
                </div>
            </div>

          </div>

          <div class="row">
            <div class="col-sm">
              <h5>Line</h5>
              <div class="form-group">
                  <select required="" name="line" class="form-control">
                     <option value="">Select Line</option>
                      <option value="Laanta 1">Laanta 1</option>
                      <option value="Laanta 2">Laanta 2</option>
                      <option value="Laanta 3">Laanta 3</option>
                      <option value="Laanta 4">Laanta 4</option>
                      <option value="Laanta 5">Laanta 5</option>
                      <option value="Laanta 6">Laanta 6</option>
                    </select>
              </div>
            </div>
            <div class="col-sm">
              <h5>Zone</h5>
              <div class="form-group">
                <input class="form-control" required type="text" name="zone" value="">
              </div>
            </div>
          </div>
          <div class="row">
             <div class="col-sm">
               <h5>Width</h5>
               <div class="form-group">
                 <input class="form-control" type="text" name="width" value="">
               </div>
             </div>
             <div class="col-sm">
               <h5>Length</h5>
               <div class="form-group">
                 <input class="form-control" type="text" name="length" value="">
               </div>
             </div>
           </div>
           <div class="row">
              <div class="col-sm">
                <h5>Area</h5>
                <div class="form-group">
                  <input class="form-control" type="text" name="area" value="">
                </div>
              </div>
            </div>


           <div class="row">
              <div class="col-sm">
                <h5>North</h5>
                <div class="form-group">
                  <input class="form-control" required type="text" name="north" value="">
                </div>
              </div>
              <div class="col-sm">
                <h5>West</h5>
                <div class="form-group">
                  <input class="form-control" required type="text" name="west" value="">
                </div>
              </div>

            </div>

            <div class="row">
               <div class="col-sm">
                 <h5>East</h5>
                 <div class="form-group">
                   <input class="form-control" required type="text" name="east" value="">
                 </div>
               </div>
               <div class="col-sm">
                 <h5>South</h5>
                 <div class="form-group">
                   <input class="form-control" required type="text" name="south" value="">
                 </div>
               </div>
             </div>

             <div class="row">
                <div class="col-sm">
                  <h5>Witness one</h5>
                  <div class="form-group">
                    <input class="form-control" required type="text" name="witness1" value="">
                  </div>
                </div>
                <div class="col-sm">
                  <h5>Witness two</h5>
                  <div class="form-group">
                    <input class="form-control" required type="text" name="witness2" value="">
                </div>
              </div>
            </div>

              <div class="row">

                 <div class="col-sm">
                   <h5>Witness three</h5>
                 <div class="form-group">
                   <input class="form-control" type="text" required name="witness3" value="">
               </div>
             </div>
         </div>

              <!--end of row 4 -->
              <input class="btn btn-primary offset-10" type="submit" value="Save">

            </form>

        </div>
      </div>
    </div>


    </div>
    <!-- end of class 12 -->
    </div>



@stop
@section('footer_scripts')
    <!--  plugin scripts -->
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/countUp.js/js/countUp.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flip/js/jquery.flip.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/js/pluginjs/jquery.sparkline.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/chartist/js/chartist.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/js/pluginjs/chartist-tooltip.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/swiper/js/swiper.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/circliful/js/jquery.circliful.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.js')}}" ></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.resize.js')}}"></script>
    <!--end of plugin scripts-->

    <script type="text/javascript" src="{{asset('assets/js/pages/index.js')}}"></script>
@stop

resources/views/lands/createland.blade.php
@extends('layouts/default')

{{-- Page title --}}
@section('title')
    Dashboard
    @parent
@stop
{{-- page level styles --}}
@section('header_styles')
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/chartist/css/chartist.min.css')}}" />
    <link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/circliful/css/jquery.circliful.css')}}">
    <link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/index.css')}}">

@stop

@section('content')

    <header class="head">
        <div class="main-bar">
            <div class="row no-gutters">
                <div class="col-6">
                    <h4 class="m-t-5">
                        <i class="fa fa-home"></i>
                        Dashboard
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="outer">

  <div class="outer">
    <div class="row">
      <div class="col-12">
        @include('lands.addmaps')

      </div>

    </div>
      <div class="inner bg-container">

<br><br>
<div class="card">
  <div class="card-header bg-white">
    Land Registration
  </div>
    <div class="card-block">
          <form method="POST" action="{{ route('lands.store') }}" accept-charset="UTF-8">
            {{ csrf_field() }}
            <br>
          <div class="row">
            <div class="col-sm">
              <h5>Latitude</h5>
              <div class="form-group">
                <input class="form-control" type="text" required id="lat"  name="latitude" value="">
              </div>

            </div>
              <div class="col-sm">
              <h5>Longitude</h5>
              <div class="form-group">
                <input class="form-control" required type="text" id="lng"  name="longitude" value="">
              </div>
            </div>
          </div>


          <div class="row">
            <div class="col-sm">
              <h5>Land Type</h5>
              <div class="form-group">
                  <select required="" name="type" required class="form-control">
                    <option value="">Select Project Land Type</option>
                      <option value="Deegaan">Deegaan</option>
                      <option value="Ganacsi">Ganacsi</option>
                      <option value="Beerid">Beerid</option>
                    </select>
              </div>

            </div>
              <div class="col-sm">
                <h5>Town</h5>
                <div class="form-group">
                    <select required name="town" class="form-control">
                      <option value="">Select Town</option>
                        <option value="Israac">Israac</option>
                        <option value="Garsoor">Garsoor</option>
                        <option value="Barwaaqo">barwaaqo</option>
                      </select>
                </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm">
              <h5>Line</h5>
              <div class="form-group">
                  <select required="" name="line" class="form-control">
                     <option value="">Select Line</option>
                      <option value="Laanta 1">Laanta 1</option>
                      <option value="Laanta 2">Laanta 2</option>
                      <option value="Laanta 3">Laanta 3</option>
                      <option value="Laanta 4">Laanta 4</option>
                      <option value="Laanta 5">Laanta 5</option>
                      <option value="Laanta 6">Laanta 6</option>
                    </select>
              </div>
            </div>
            <div class="col-sm">
              <h5>Zone</h5>
              <div class="form-group">
                <input class="form-control" required type="text" name="zone" value="">
              </div>
            </div>
          </div>

          <div class="row">
             <div class="col-sm">
               <h5>Width (Meter)</h5>
               <div class="form-group">
                 <input class="form-control" type="text" name="width" value="">
               </div>
             </div>
             <div class="col-sm">
               <h5>Length (Meter)</h5>
               <div class="form-group">
                 <input class="form-control" type="text" name="length" value="">
               </div>
             </div>
           </div>
           <div class="row">
              <div class="col-sm">
                <h5>Area</h5>
                <div class="form-group">
                  <input class="form-control" type="text" name="area" value="">
                </div>
              </div>

              <div class="col-sm">
                <h5 class="invisible">test</h5>
                <div class="form-group">
                  <input class="form-control" required type="text" name="north" value="" disabled>
                </div>
              </div>
            </div>


           <div class="row">
              <div class="col-sm">
                <h5>North</h5>
                <div class="form-group">
                  <input class="form-control" required type="text" name="north" value="">
                </div>
              </div>
              <div class="col-sm">
                <h5>West</h5>
                <div class="form-group">
                  <input class="form-control" required type="text" name="west" value="">
                </div>
              </div>

            </div>

            <div class="row">
               <div class="col-sm">
                 <h5>East</h5>
                 <div class="form-group">
                   <input class="form-control" required type="text" name="east" value="">
                 </div>
               </div>
               <div class="col-sm">
                 <h5>South</h5>
                 <div class="form-group">
                   <input class="form-control" required type="text" name="south" value="">
                 </div>
               </div>
             </div>

             <div class="row">
                <div class="col-sm">
                  <h5>Witness one</h5>
                  <div class="form-group">
                    <input class="form-control" required type="text" name="witness1" value="">
                  </div>
                </div>
                <div class="col-sm">
                  <h5>Witness two</h5>
                  <div class="form-group">
                    <input class="form-control" required type="text" name="witness2" value="">
                </div>
              </div>
            </div>

              <div class="row">

                 <div class="col-sm">
                   <h5>Witness three</h5>
                 <div class="form-group">
                   <input class="form-control" type="text" required name="witness3" value="">
               </div>
             </div>
             <div class="col-sm">
               <h5 class="invisible">test</h5>
               <div class="form-group">
                 <input class="form-control" required type="text" name="north" value="" disabled>
               </div>
             </div>
         </div>

              <!--end of row 4 -->
              <input class="btn btn-primary offset-10" type="submit" value="Save">

            </form>

        </div>
      </div>
    </div>


    </div>
    <!-- end of class 12 -->
    </div>
@stop
@section('footer_scripts')
    <!--  plugin scripts -->
    <script type="text/javascript" src="{{asset('assets/vendors/countUp.js/js/countUp.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flip/js/jquery.flip.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/js/pluginjs/jquery.sparkline.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/chartist/js/chartist.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/js/pluginjs/chartist-tooltip.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/swiper/js/swiper.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/circliful/js/jquery.circliful.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.js')}}" ></script>
    <script type="text/javascript" src="{{asset('assets/vendors/flotchart/js/jquery.flot.resize.js')}}"></script>
    <!--end of plugin scripts-->

    <script type="text/javascript" src="{{asset('assets/js/pages/index.js')}}"></script>
@stop

resources/views/lands/index.blade.php
@extends('layouts/default')

{{-- Page title --}}
@section('title')
    Dashboard
    @parent
@stop
{{-- page level styles --}}
@section('header_styles')
<link type="text/css" rel="stylesheet" href="{{asset('assets/vendors/select2/css/select2.min.css')}}"/>
   <link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/dataTables.bootstrap.css')}}"/>
   <!--End of plugin styles-->
   <!--Page level styles-->
   <link type="text/css" rel="stylesheet" href="{{asset('assets/css/pages/tables.css')}}"/>
   <!-- end of page level styles -->
@stop
@section('content')

    <header class="head">
        <div class="main-bar">
            <div class="row no-gutters">
                <div class="col-6">
                    <h4 class="m-t-5">
                        <i class="fa fa-home"></i>
                        Dashboard
                    </h4>
                </div>
            </div>
        </div>
    </header>
    <div class="outer">
        <div class="inner bg-container">
          <div class="row">
            <div class="col-12">
              @section('maptitle', 'Overview of registred Lands')

            </div>

          </div>
            <div class="card">
                <div class="card-header bg-warning">
                     Land List
                </div>
                <div class="card-block m-t-35" id="user_body">
                    <div class="table-toolbar">
                        <div class="btn-group">

                            </a>
                        </div>
                        <div class="btn-group float-xs-right users_grid_tools">
                            <div class="tools"></div>
                        </div>
                    </div>
                    <div>
                        <div>
                              <table class="table  table-striped table-bordered table-hover dataTable no-footer"
                                       id="editable_table" data-order='[[ 8, "dec" ]]' role="grid">
                                  <thead>
                              <tr>
                                <th>Owner ID</th>
                                <th>Type</th>
                                <th>town</th>
                                <th>laanta</th>
                                <th>Zone</th>
                                <th>width</th>
                                <th>length</th>
                                <th>Area of Land</th>
                                <th>Created</th>
                                <th class="actions">Actions</th>
                              </tr>
                              </thead>
                              <tbody>
                                @foreach ($lands as $land)
                                <tr>
                                  <td><a href="{{route('owners.show', [$land->owner->id])}}">{{$land->owner->pid}}</a></td>

                                  <td>{{$land->type}}</td>
                                  <td>{{$land->town}}</td>
                                  <td>{{$land->laanta}}</td>
                                  <td>{{$land->zone}}</td>
                                  <td>{{$land->width}}</td>
                                  <td>{{$land->length}}</td>
                                  <td>{{$land->areaofland}}</td>
                                  <td>{{ $land->created_at->format('d/m/Y') }}</td>

                                  <td class="no-sort no-click" id="bread-actions">


                                  <a href="{{route('lands.show', [$land->id])}}" title="View" class="btn btn-sm btn-warning pull-right">
                                  <i class="fa fa-eye"></i> <span class="hidden-xs hidden-sm">View   </span>
                                  </a>
                                  </td>
                                </tr>
            @endforeach
          </tbody>

</table>
</div>

<!-- <a href="{{route('lands.edit', [$land->id])}}" title="Transfer" class="btn btn-sm btn-primary pull-right edit">
<i class="fa fa-edit"></i> <span class="hidden-xs hidden-sm">Transfer</span>
</a> -->

        </div>
    </div>
@stop
@section('footer_scripts')

<!--Plugin scripts-->
   <script type="text/javascript" src="{{asset('assets/vendors/select2/js/select2.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/jquery.dataTables.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.bootstrap.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.responsive.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/dataTables.buttons.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.colVis.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.html5.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.bootstrap.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.print.min.js')}}"></script>
   <script type="text/javascript" src="{{asset('assets/vendors/datatables/js/buttons.print.min.js')}}"></script>

<script type="text/javascript">


</script>
   <!--End of plugin scripts-->
   <!--Page level scripts-->
   <script type="text/javascript" src="{{asset('assets/js/pages/users.js')}}"></script>
   <!-- end page level scripts -->

@stop